
// database
export const SET_DB_CONN = "SET_DB_CONN"

// admin
export const SET_ADMIN = "SET_ADMIN"
export const CHANGE_ADMIN_NAME = "CHANGE_ADMIN_NAME"

// contact 
export const SET_CONTACTS = "SET_CONTACTS"
export const ADD_NEW_CONTACT = "ADD_NEW_CONTACT"
export const DELETE_CONTACTS = "DELETE_CONTACTS"

// message
export const SET_MESSAGES = "SET_MESSAGES"
export const NEW_MESSAGE = "NEW_MESSAGE"
export const DELETE_MESSAGES = "DELETE_MESSAGES"
export const SET_DECRYPTED_MESSAGE = "SET_DECRYPTED_MESSAGE"
export const DELETE_CHATS = "DELETE_CHATS"

// alert
export const SHOW_ALERT = "SHOW_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"

// realtime db
export const CONNECT_REALTIME_DB = "CONNECT_REALTIME_DB"

// delete actions
export const SELECT_CONTACT_TO_DELETE = "SELECT_CONTACT_TO_DELETE"
export const DESELECT_CONTACT_TO_DELETE = "DESELECT_CONTACT_TO_DELETE"
export const DESELECT_ALL_CONTACTS_TO_DELETE = "DESELECT_ALL_CONTACTS_TO_DELETE"

export const SELECT_CHAT_TO_DELETE = "SELECT_CHAT_TO_DELETE"
export const DESELECT_CHAT_TO_DELETE = "DESELECT_CHAT_TO_DELETE"
export const DESELECT_ALL_CHATS_TO_DELETE = "DESELECT_ALL_CHATS_TO_DELETE"

export const SELECT_MESSAGE_TO_DELETE = "SELECT_MESSAGE_TO_DELETE"
export const DESELECT_MESSAGE_TO_DELETE = "DESELECT_MESSAGE_TO_DELETE"
export const DESELECT_ALL_MESSAGES_TO_DELETE = "DESELECT_ALL_MESSAGES_TO_DELETE"

// network connectivity actions
export const SET_NETWORK_CONNECTION = "SET_NETWORK_CONNECTION"

// new message notifications
export const INCREMENT_NOTIFICATION_COUNTER = "INCREMENT_NOTIFICATION_COUNTER"
export const CLEAR_NOTIFICATION_COUNTER = "CLEAR_NOTIFICATION_COUNTER"
export const SET_LISTEN_NOTIFICATION_CHANGES = "SET_LISTEN_NOTIFICATION_CHANGES"