export const MESSAGE_SENT = 0
export const MESSAGE_RECEIVED = 1

export const REFRESH_CHATS = "REFRESH_CHATS"
export const REFRESH_CONTACTS = "REFRESH_CONTACTS"

export const DELETING_CHATS = "DELETING_CHATS"
export const DELETING_CONTACTS = "DELETING_CONTACTS"
export const DELETING_MESSAGES = "DELETING_MESSAGES"

export const SENDING_MESSAGE = "SENDING_MESSAGE"

export const CHAT_MESSAGE_PAGE_LIMIT = 50