const avatarImages = [
    'http://cdn.securechat.flaviorajta.com:8080/images/png/001-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/002-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/003-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/004-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/005-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/006-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/007-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/008-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/009-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/010-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/011-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/012-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/013-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/014-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/015-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/016-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/017-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/018-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/019-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/020-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/021-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/022-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/023-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/024-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/025-lego.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/026-ninja.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/027-cowboy.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/028-knight.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/029-explorer.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/030-scuba diver.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/031-clown.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/032-boy.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/033-native american.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/034-cashier.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/035-spy.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/036-mariachi.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/037-pirate.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/038-fisherman.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/039-cyborg.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/040-vampire.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/041-businessman.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/042-conquistador.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/043-DJ.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/044-american football player.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/045-cheerleader.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/046-santa claus.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/047-diver.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/048-thespian.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/049-man.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/050-man.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/051-cowgirl.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/052-caveman.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/053-witch.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/054-vampire.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/055-queen.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/056-gnome.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/057-injured.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/058-thief.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/059-hiker.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/060-devil.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/061-desert.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/062-ninja.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/063-batman.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/064-superman.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/065-wolverine.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/066-Spiderman.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/067-dummy.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/068-magician.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/069-thor.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/070-deadpool.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/071-businessman.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/072-woman.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/073-mummy.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/074-singer.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/075-Mohawk.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/076-explorer.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/077-dentist.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/078-hip hop.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/079-surgeon.png',
    'http://cdn.securechat.flaviorajta.com:8080/images/png/080-priest.png',
]

exports.getRandomAvatar = () => {
    return avatarImages[Math.floor(Math.random() * avatarImages.length)]
}

exports.avatarThumbnails = avatarImages